# This is a basic workflow to show how to use GITHUB_TOKEN
name: hello-world
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!" ${{ secrets.GITHUB_TOKEN }} 'or'  ${{ github.token }}
